version: '3.8'

services:
  # 1. The Real Redis Server
  redis:
    image: redis:alpine
    container_name: redis_thesis
    ports:
      - "6379:6379"
    restart: always

  # 2. PostgreSQL Database (Stores your metrics)
  postgres:
    image: postgres:15-alpine
    container_name: postgres_thesis
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: redis_metrics_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # 3. pgAdmin (Web GUI to view the Database)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_thesis
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@thesis.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: